force-app/main/default/objects/Customer_Success_Story__c/Customer_Success_Story__c.object-meta.xml
<CustomObject>
    <label>Customer Success Story</label>
    <nameField>
        <label>Customer Success Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Success Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Success_Story__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account that is giving positive feedback on product</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Success Stories</relationshipLabel>
    <relationshipName>Customer_Success_Stories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Success_Story__c/fields/Success_Rating__c.field-meta.xml
<CustomField>
    <fullName>Success_Rating__c</fullName>
    <label>Success Rating</label>
    <precision>3</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CustomerStoryTriggerTest.cls
/*Created By: Khalil Newsome
 * Last Updated: 03/26/2023
 * Description: Test for CustomerStoryTrigger
 */
@isTest
public class CustomerStoryTriggerTest {

    
    @isTest
    static void TP_BeforeInsert(){
        Customer_Success_Story__c tpTest= new Customer_Success_Story__c();
        tpTest= new Customer_Success_Story__c(Name='Test', Success_Rating__c=5,Account__c='0018b00002Mf5iaAAB');
        insert tpTest;
        
        tpTest.Success_Rating__c= 3;
        update tpTest;
    }
    
    
}