force-app/main/default/objects/Customer_Success_Story__c/Customer_Success_Story__c.object-meta.xml
<CustomObject>
    <label>Customer Success Story</label>
    <nameField>
        <label>Customer Success Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Success Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Success_Story__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account that is giving positive feedback on product</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Success Stories</relationshipLabel>
    <relationshipName>Customer_Success_Stories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Success_Story__c/fields/Success_Rating__c.field-meta.xml
<CustomField>
    <fullName>Success_Rating__c</fullName>
    <label>Success Rating</label>
    <precision>3</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CustomerStoryHelperTest.cls
@isTest
public class CustomerStoryHelperTest {
    
    @isTest
    public static void TP_RankAssignment(){
        
        List<Customer_Success_Story__c> tpTestList= new List<Customer_Success_Story__c>();
        tpTestList.add(new Customer_Success_Story__c(Name='TP Test', Success_Rating__c=3,Account__c='0018b00002Mf5iaAAB'));
        CustomerStoryHelper.rankAssignment(tpTestList);
    } 
    
    @isTest
    public static void TN_RankAssignment(){
        List<Customer_Success_Story__c> tnTestList= new List<Customer_Success_Story__c>();
        tnTestList.add(new Customer_Success_Story__c(Name='TN Test', Success_Rating__c=8,Account__c='0018b00002Mf5iaAAB'));
        CustomerStoryHelper.rankAssignment(tnTestList);
    }
    @isTest
    public static void TP_UpdateRankAndSortList(){
        List<Customer_Success_Story__c> tpTestList= new List<Customer_Success_Story__c>();
        tpTestList.add(new Customer_Success_Story__c(Name='TP Test', Success_Rating__c=3,Account__c='0018b00002Mf5iaAAB'));
        tpTestList.add(new Customer_Success_Story__c(Name='TPTest', Success_Rating__c=4.3,Account__c='0018b00002Mf5iaAAB'));
        List<Customer_Success_Story__c> tpTestList2= new List<Customer_Success_Story__c>();
        tpTestList2.add(new Customer_Success_Story__c(Name='TP Test2', Success_Rating__c=3.1,Account__c='0018b00002Mf5iaAAB'));
        
        CustomerStoryHelper.sortList(tpTestList);
        CustomerStoryHelper.updateRank(tpTestList,tpTestList2);
        
        List<Customer_Success_Story__c >tpTestList3 = new List<Customer_Success_Story__c>();
        tpTestList3.addAll(tpTestList);
        CustomerStoryHelper.updateRank(tpTestList,tpTestList3);
    }
  
    
    @isTest
    public static void TN_UpdateRank(){
        List<Customer_Success_Story__c> tnTestList= new List<Customer_Success_Story__c>();
        tnTestList.add(new Customer_Success_Story__c(Name='TN Test', Success_Rating__c=8,Account__c='0018b00002Mf5iaAAB'));
        List<Customer_Success_Story__c> tnTestList2= new List<Customer_Success_Story__c>();
        tnTestList.add(new Customer_Success_Story__c(Name='TN Test', Success_Rating__c=5,Account__c='0018b00002Mf5iaAAB'));
        CustomerStoryHelper.updateRank(tnTestList,tntestList2);
        
        
        
    }
}